#Feedback Server   

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/feedback?autoReconnect=true&useSSL=false 
        username: root 
        password: vengatesanns@freak  
    jpa:
       hibernate.ddl-auto: update    
       show-sql:  true
       generate-ddl: false    