#My App - Server (Task Service)


spring:
	datasource:
	        url: jdbc:mysql://localhost:3306/my_app_db?autoReconnect=true&useSSL=false 
	        username: root 
	        password: vengatesanns@freak  
	 jpa:
	       hibernate.ddl-auto: none
	       show-sql:  true
	       generate-ddl: false     
	 jackson: 
	          serialization:
	               write-dates-as-timestamps: false   