#My App - Server (Task Service)


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/task-service_db?autoReconnect=true&useSSL=false 
        username: root 
        password: vengatesanns@freak  
    jpa:
       hibernate.ddl-auto: update    
       show-sql:  true
       generate-ddl: false    