#My App - Server (Task Service)


spring:
  jackson: 
      serialization:
           write-dates-as-timestamps: false   
  datasource:
     url: jdbc:mysql://localhost:3306/task_service_db?autoReconnect=true&useSSL=false 
     username: root 
     password: vengatesanns@freak  
  jpa:
     hibernate.ddl-auto: none
     show-sql:  true
     generate-ddl: false     